stages:
  # - codestyle
  - test
  - buildtag
  - deploy
  
variables:
  GIT_DEPTH: "20"
  GIT_SUBMODULE_STRATEGY: "none"
  GET_SOURCES_ATTEMPTS: "3"
  # local gitlab ci functions path
  LOCAL_CI_FUNCS_PATH: .gitlab-ci-functions
  # java codestyle check path
  JAVA_CODESTYLE_CHECK_PATH: src/main/java

include:
  # register bash functions and local ci functions
  - project: infrastructure/gitlab-ci-functions
    ref: master
    file: templates/.register-gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
  - project: infrastructure/gitlab-ci-functions
    ref: master
    file: templates/merge.gitlab-ci.yml

